const { Engine, World, Bodies, Mouse, MouseConstraint, Constraint } = Matter;
let ground;
const boxes = [];
let bird;
let world, engine;
let mConstraint;
let slingshot;
let birdImg, boxImg, bkgImg, minnionPigImg;
let slingShotImgLeft, slingShotImgRight;
let slingShotBandFront, slingShotBandBack;
let minnionPig;
